# Generated by Django 4.2.2 on 2023-06-28 07:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0002_alter_user_is_staff")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        )
    ]
